#!/usr/bin/env bash
# Regenerate Python bindings for tabula.wire.v1 from chat.proto.
#
# Output layout (under wire/src/tabula_wire/proto/v1/):
#   chat_pb2.py    (generated by protoc)
#   chat_pb2.pyi   (generated by protoc --pyi_out)
#
# Per the canonical layout (issue #57), generated bindings live at the
# normal package path `tabula_wire.proto.v1` — not under a `gen/` tree.
# `wire/proto/chat.proto` stays flat; `protoc -I wire/proto` is the
# source dir.
#
# Usage:
#   ./build.sh           # regenerate in place
#   ./build.sh --check   # regenerate to a tmp dir, fail if it differs
#                        # from the checked-in copy (CI verification)
#
# Requirements:
#   - protoc >= 3.20 (tested with 34.1; pin in README)
#   - Python protobuf runtime (`pip install protobuf`) at import time

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# wire/proto -> wire (parent of script dir)
WIRE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROTO_SRC_DIR="$SCRIPT_DIR"
OUT_DIR="$WIRE_DIR/src/tabula_wire/proto/v1"

mode="write"
if [[ "${1:-}" == "--check" ]]; then
  mode="check"
elif [[ -n "${1:-}" ]]; then
  echo "Unknown argument: $1" >&2
  echo "Usage: $0 [--check]" >&2
  exit 2
fi

regen() {
  local target="$1"
  mkdir -p "$target"
  protoc \
    -I "$PROTO_SRC_DIR" \
    --python_out="$target" \
    --pyi_out="$target" \
    chat.proto
}

if [[ "$mode" == "check" ]]; then
  TMP_DIR="$(mktemp -d)"
  trap 'rm -rf "$TMP_DIR"' EXIT
  regen "$TMP_DIR"

  fail=0
  for f in chat_pb2.py chat_pb2.pyi; do
    if ! diff -q "$TMP_DIR/$f" "$OUT_DIR/$f" >/dev/null 2>&1; then
      echo "ERROR: $OUT_DIR/$f is out of date with chat.proto" >&2
      diff "$OUT_DIR/$f" "$TMP_DIR/$f" >&2 || true
      fail=1
    fi
  done
  if [[ "$fail" -ne 0 ]]; then
    echo "Run wire/proto/build.sh and commit the result." >&2
    exit 1
  fi
  echo "OK: generated bindings match chat.proto"
  exit 0
fi

regen "$OUT_DIR"
echo "Wrote $OUT_DIR/chat_pb2.py and $OUT_DIR/chat_pb2.pyi"
