#!/usr/bin/env bash
# Regenerate Python bindings for tabula.wire.v1 from chat.proto.
#
# Output layout (under wire/proto/gen/):
#   tabula/__init__.py          (namespace package shim)
#   tabula/wire/__init__.py     (namespace package shim)
#   tabula/wire/v1/__init__.py  (re-exports from chat_pb2)
#   tabula/wire/v1/chat_pb2.py  (generated by protoc)
#
# Usage: ./build.sh
#
# Requirements:
#   - protoc >= 3.20 (tested with 34.1; pin in README)
#   - Python protobuf runtime (`pip install protobuf`) at import time

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

OUT_DIR="gen/tabula/wire/v1"
mkdir -p "$OUT_DIR"

# Empty namespace __init__.py files so the package is importable.
: > "gen/tabula/__init__.py"
: > "gen/tabula/wire/__init__.py"

# Generate chat_pb2.py to a tmp location, then drop it into the package.
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

protoc --python_out="$TMP_DIR" --proto_path=. chat.proto
mv "$TMP_DIR/chat_pb2.py" "$OUT_DIR/chat_pb2.py"

# __init__.py re-exports the generated symbols so callers can write:
#   from tabula.wire.v1 import ClientFrame, ServerFrame, ...
cat > "$OUT_DIR/__init__.py" <<'PY'
"""tabula.wire.v1 — generated protobuf bindings for the Noise-framed chat schema.

Regenerate with `wire/proto/build.sh`. Do not hand-edit `chat_pb2.py`.

The wire schema is frozen at v1; new fields are additive only.
See `wire/proto/README.md` for the full v1 contract.
"""

from .chat_pb2 import (  # noqa: F401
    AssistantToken,
    AssistantTurnEnd,
    ClientFrame,
    EndSession,
    ErrorFrame,
    Hello,
    ServerFrame,
    UserMessage,
    Welcome,
)

# Wire protocol version. Carried in `Hello.protocol_version` and echoed in
# `Welcome.protocol_version`. Bumped only on breaking changes.
PROTOCOL_VERSION = 1

__all__ = [
    "PROTOCOL_VERSION",
    "AssistantToken",
    "AssistantTurnEnd",
    "ClientFrame",
    "EndSession",
    "ErrorFrame",
    "Hello",
    "ServerFrame",
    "UserMessage",
    "Welcome",
]
PY

echo "Wrote $OUT_DIR/chat_pb2.py and $OUT_DIR/__init__.py"
